version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ${DOCKER_VOLUME_DOCKER}/Dockerfile
    container_name: ${DOCKER_PROJECT_NAME}-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - ${DOCKER_NGINX_PORT}:80